GET http://localhost:3000/hello

###

GET http://43.202.40.119:80/health

###

GET http://ec2-43-202-40-119.ap-northeast-2.compute.amazonaws.com:80/health

###

GET http://ec2-43-202-40-119.ap-northeast-2.compute.amazonaws.com:80/bye